//! Static game data, generated by `tools/gen-assets` and compiled in.
//!
//! Nothing here ever changes at runtime, so quests and inventories refer to
//! monsters and items by index rather than carrying copies around. That keeps
//! the serialised [`crate::GameState`] small enough to live in one row.

use std::sync::LazyLock;

use serde::{Deserialize, Serialize};

use crate::dice::Die;
use crate::numeric::Cr;

const MONSTERS_JSON: &str = include_str!("../assets/monsters.json");
const WEAPONS_JSON: &str = include_str!("../assets/weapons.json");
const ARMOR_JSON: &str = include_str!("../assets/armor.json");
const COMPAT_JSON: &str = include_str!("../assets/compat.json");

/// Rarity exponent for the shop: cost^GAMMA is an item's relative weight, so
/// expensive gear shows up less often. The reference moved this from -0.3 to
/// -0.25 in 0.4 to make expensive items a little more probable.
pub const SHOP_GAMMA: f64 = -0.25;

pub type MonsterId = u16;
pub type ItemId = u16;

// ---------------------------------------------------------------------------
// monsters
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Deserialize)]
pub struct MonsterAttack {
    #[serde(rename = "atk")]
    pub attack_bonus: i32,
    #[serde(rename = "dmg")]
    pub damage: Vec<Die>,
    #[serde(rename = "bonus")]
    pub damage_bonus: i32,
}

#[derive(Debug, Clone, Deserialize)]
pub struct Monster {
    pub name: String,
    #[serde(rename = "type")]
    pub kind: String,
    pub size: u8,
    pub alignment: u8,
    pub ac: i32,
    pub dex: i32,
    pub hit_dice: Die,
    #[serde(rename = "cr8")]
    pub cr: Cr,
    pub attacks: Vec<MonsterAttack>,
    /// Set only for the Cloud Giant, which is "neutral good (50%) or neutral
    /// evil (50%)" and resolves by a coin flip when a quest is built.
    #[serde(default)]
    pub alignment_alt: Option<u8>,
}

// ---------------------------------------------------------------------------
// equipment
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Deserialize)]
struct RawWeapon {
    name: String,
    cost: i64,
    weight: i64,
    dice_count: u32,
    dice_value: u32,
}

#[derive(Debug, Clone, Deserialize)]
struct RawArmor {
    name: String,
    cost: i64,
    weight: i64,
    base: i32,
    dex_bonus: bool,
    max_bonus: Option<i32>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ItemKind {
    Weapon,
    Armor,
}

#[derive(Debug, Clone)]
pub enum ItemStats {
    Weapon {
        damage: Die,
    },
    Armor {
        base: i32,
        dex_bonus: bool,
        max_bonus: Option<i32>,
    },
}

/// One buyable line in Absalom's store.
///
/// Weapons and armors share a single index space, exactly as the reference does
/// (`items = weapons + armors`, each sorted by cost), so a player types one
/// number regardless of what they are buying.
#[derive(Debug, Clone)]
pub struct Item {
    pub id: ItemId,
    pub name: String,
    /// Normalised to copper: 1 gp = 10 sp = 100 cp.
    pub cost: i64,
    pub weight: i64,
    pub stats: ItemStats,
}

impl Item {
    pub fn kind(&self) -> ItemKind {
        match self.stats {
            ItemStats::Weapon { .. } => ItemKind::Weapon,
            ItemStats::Armor { .. } => ItemKind::Armor,
        }
    }

    /// Weapons are displayed as `[id]`, armors as `{id}`.
    pub fn tag(&self) -> String {
        match self.kind() {
            ItemKind::Weapon => format!("[{}]", self.id),
            ItemKind::Armor => format!("{{{}}}", self.id),
        }
    }
}

// ---------------------------------------------------------------------------
// alignment / size compatibility
// ---------------------------------------------------------------------------

/// Which monsters will share a quest with which, lifted verbatim out of the
/// reference's `pickup_random` elif chains by the asset generator.
#[derive(Debug, Deserialize)]
pub struct Compat {
    pub alignments: Vec<String>,
    pub alignment_compatible: Vec<Vec<bool>>,
    pub sizes: Vec<String>,
    pub size_compatible: Vec<Vec<bool>>,
}

impl Compat {
    pub fn alignments_agree(&self, a: u8, b: u8) -> bool {
        self.alignment_compatible[a as usize][b as usize]
    }

    pub fn sizes_agree(&self, a: u8, b: u8) -> bool {
        self.size_compatible[a as usize][b as usize]
    }
}

// ---------------------------------------------------------------------------
// monster pools
// ---------------------------------------------------------------------------

/// The four difficulty pools a quest draws from. They deliberately overlap,
/// matching the reference's CR bands.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Pool {
    /// CR <= 1
    Easy,
    /// 1 < CR <= 10
    Medium1,
    /// 5 < CR <= 16
    Medium2,
    /// CR > 13
    Difficult,
}

impl Pool {
    /// `dif` is `randrange(0, 10)`: 30% easy, 20% / 20% medium, 30% difficult.
    pub fn for_difficulty(dif: i64) -> Pool {
        match dif {
            d if d < 3 => Pool::Easy,
            d if d < 5 => Pool::Medium1,
            d if d < 7 => Pool::Medium2,
            _ => Pool::Difficult,
        }
    }

    fn contains(self, cr: Cr) -> bool {
        let cr = cr.eighths();
        match self {
            Pool::Easy => cr <= 8,
            Pool::Medium1 => cr > 8 && cr <= 80,
            Pool::Medium2 => cr > 40 && cr <= 128,
            Pool::Difficult => cr > 104,
        }
    }

    pub fn members(self) -> &'static [MonsterId] {
        let pools = &*POOLS;
        match self {
            Pool::Easy => &pools.easy,
            Pool::Medium1 => &pools.medium1,
            Pool::Medium2 => &pools.medium2,
            Pool::Difficult => &pools.difficult,
        }
    }
}

struct Pools {
    easy: Vec<MonsterId>,
    medium1: Vec<MonsterId>,
    medium2: Vec<MonsterId>,
    difficult: Vec<MonsterId>,
}

// ---------------------------------------------------------------------------
// loading
// ---------------------------------------------------------------------------

static MONSTERS: LazyLock<Vec<Monster>> = LazyLock::new(|| {
    serde_json::from_str(MONSTERS_JSON).expect("assets/monsters.json is malformed")
});

static COMPAT: LazyLock<Compat> = LazyLock::new(|| {
    let compat: Compat =
        serde_json::from_str(COMPAT_JSON).expect("assets/compat.json is malformed");
    let a = compat.alignments.len();
    let s = compat.sizes.len();
    assert_eq!(compat.alignment_compatible.len(), a, "alignment matrix is not square");
    assert!(compat.alignment_compatible.iter().all(|row| row.len() == a));
    assert_eq!(compat.size_compatible.len(), s, "size matrix is not square");
    assert!(compat.size_compatible.iter().all(|row| row.len() == s));
    compat
});

static ITEMS: LazyLock<Vec<Item>> = LazyLock::new(|| {
    let mut weapons: Vec<RawWeapon> =
        serde_json::from_str(WEAPONS_JSON).expect("assets/weapons.json is malformed");
    let mut armors: Vec<RawArmor> =
        serde_json::from_str(ARMOR_JSON).expect("assets/armor.json is malformed");

    // Stable sorts, so equal-cost items keep their catalogue order as in Python.
    weapons.sort_by_key(|w| w.cost);
    armors.sort_by_key(|a| a.cost);

    let weapon_items = weapons.into_iter().map(|w| Item {
        id: 0,
        name: w.name,
        cost: w.cost,
        weight: w.weight,
        stats: ItemStats::Weapon { damage: Die::new(w.dice_count, w.dice_value) },
    });
    let armor_items = armors.into_iter().map(|a| Item {
        id: 0,
        name: a.name,
        cost: a.cost,
        weight: a.weight,
        stats: ItemStats::Armor {
            base: a.base,
            dex_bonus: a.dex_bonus,
            max_bonus: a.max_bonus,
        },
    });

    weapon_items
        .chain(armor_items)
        .enumerate()
        .map(|(i, mut item)| {
            item.id = i as ItemId;
            item
        })
        .collect()
});

static POOLS: LazyLock<Pools> = LazyLock::new(|| {
    let collect = |pool: Pool| -> Vec<MonsterId> {
        MONSTERS
            .iter()
            .enumerate()
            .filter(|(_, m)| pool.contains(m.cr))
            .map(|(i, _)| i as MonsterId)
            .collect()
    };
    Pools {
        easy: collect(Pool::Easy),
        medium1: collect(Pool::Medium1),
        medium2: collect(Pool::Medium2),
        difficult: collect(Pool::Difficult),
    }
});

static SHOP_TOTAL_WEIGHT: LazyLock<f64> =
    LazyLock::new(|| items().iter().map(|i| (i.cost as f64).powf(SHOP_GAMMA)).sum());

pub fn monsters() -> &'static [Monster] {
    &MONSTERS
}

pub fn monster(id: MonsterId) -> &'static Monster {
    &MONSTERS[id as usize]
}

pub fn items() -> &'static [Item] {
    &ITEMS
}

pub fn item(id: ItemId) -> Option<&'static Item> {
    ITEMS.get(id as usize)
}

pub fn compat() -> &'static Compat {
    &COMPAT
}

pub fn shop_total_weight() -> f64 {
    *SHOP_TOTAL_WEIGHT
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_full_bestiary_loads() {
        assert_eq!(monsters().len(), 325);
    }

    #[test]
    fn exactly_one_monster_has_a_variable_alignment() {
        let variable: Vec<_> = monsters()
            .iter()
            .filter(|m| m.alignment_alt.is_some())
            .map(|m| m.name.as_str())
            .collect();
        assert_eq!(variable, vec!["Cloud Giant"]);
    }

    #[test]
    fn twenty_three_monsters_cannot_deal_damage() {
        // Frog and Sea Horse have no actions at all; the rest have only
        // non-damaging ones. They can still be targets, never attackers.
        let harmless = monsters().iter().filter(|m| m.attacks.is_empty()).count();
        assert_eq!(harmless, 23);
    }

    #[test]
    fn pools_cover_the_reference_bands_and_overlap() {
        assert_eq!(Pool::Easy.members().len(), 138);
        assert_eq!(Pool::Medium1.members().len(), 137);
        assert_eq!(Pool::Medium2.members().len(), 67);
        assert_eq!(Pool::Difficult.members().len(), 33);
        assert!(Pool::Easy.members().iter().all(|&i| monster(i).cr <= Cr::ONE));
        assert!(Pool::Difficult.members().iter().all(|&i| monster(i).cr > Cr::from_whole(13)));
    }

    #[test]
    fn difficulty_roll_maps_to_the_documented_split() {
        let picks: Vec<Pool> = (0..10).map(Pool::for_difficulty).collect();
        assert_eq!(picks.iter().filter(|p| **p == Pool::Easy).count(), 3);
        assert_eq!(picks.iter().filter(|p| **p == Pool::Medium1).count(), 2);
        assert_eq!(picks.iter().filter(|p| **p == Pool::Medium2).count(), 2);
        assert_eq!(picks.iter().filter(|p| **p == Pool::Difficult).count(), 3);
    }

    #[test]
    fn the_store_catalogue_is_ordered_by_cost_within_each_category() {
        let items = items();
        assert_eq!(items.len(), 40, "28 weapons + 12 armors");

        let weapons: Vec<_> = items.iter().filter(|i| i.kind() == ItemKind::Weapon).collect();
        let armors: Vec<_> = items.iter().filter(|i| i.kind() == ItemKind::Armor).collect();
        assert_eq!(weapons.len(), 28);
        assert_eq!(armors.len(), 12);

        assert!(weapons.windows(2).all(|w| w[0].cost <= w[1].cost));
        assert!(armors.windows(2).all(|w| w[0].cost <= w[1].cost));
        // Weapons occupy the low ids, armors the high ones.
        assert!(weapons.iter().all(|w| w.id < 28));
        assert!(armors.iter().all(|a| a.id >= 28));
    }

    #[test]
    fn ids_are_positions_and_costs_are_in_copper() {
        for (i, item) in items().iter().enumerate() {
            assert_eq!(item.id as usize, i);
        }
        let cheapest = &items()[0];
        assert_eq!((cheapest.name.as_str(), cheapest.cost), ("Club", 10));
        let dearest = items().iter().max_by_key(|i| i.cost).unwrap();
        assert_eq!((dearest.name.as_str(), dearest.cost), ("Plate", 150_000));
    }

    #[test]
    fn items_are_tagged_by_category() {
        let club = item(0).unwrap();
        assert_eq!(club.tag(), "[0]");
        let first_armor = items().iter().find(|i| i.kind() == ItemKind::Armor).unwrap();
        assert_eq!(first_armor.tag(), format!("{{{}}}", first_armor.id));
    }

    #[test]
    fn compatibility_matrices_are_square_and_symmetric() {
        let c = compat();
        assert_eq!(c.alignments.len(), 15);
        assert_eq!(c.sizes.len(), 6);
        for i in 0..c.alignments.len() {
            for j in 0..c.alignments.len() {
                assert_eq!(
                    c.alignment_compatible[i][j], c.alignment_compatible[j][i],
                    "alignment matrix asymmetric at {i},{j}"
                );
            }
        }
        for i in 0..c.sizes.len() {
            for j in 0..c.sizes.len() {
                assert_eq!(c.size_compatible[i][j], c.size_compatible[j][i]);
            }
        }
    }

    #[test]
    fn compatibility_reproduces_spot_rules_from_the_reference() {
        let c = compat();
        let a = |name: &str| c.alignments.iter().position(|x| x == name).unwrap() as u8;
        let s = |name: &str| c.sizes.iter().position(|x| x == name).unwrap() as u8;

        // Straight from the elif chain in quest.pickup_random.
        assert!(c.alignments_agree(a("lawful good"), a("lawful good")));
        assert!(!c.alignments_agree(a("lawful good"), a("chaotic evil")));
        assert!(c.alignments_agree(a("unaligned"), a("chaotic evil")));
        assert!(!c.alignments_agree(a("neutral"), a("neutral evil")));
        assert!(c.alignments_agree(a("any evil alignment"), a("lawful evil")));

        assert!(c.sizes_agree(s("Medium"), s("Large")));
        assert!(!c.sizes_agree(s("Tiny"), s("Large")));
        assert!(!c.sizes_agree(s("Small"), s("Gargantuan")));
        assert!(c.sizes_agree(s("Huge"), s("Gargantuan")));
    }

    #[test]
    fn every_monster_indexes_valid_alignment_and_size_slots() {
        let c = compat();
        for m in monsters() {
            assert!((m.alignment as usize) < c.alignments.len(), "{}", m.name);
            assert!((m.size as usize) < c.sizes.len(), "{}", m.name);
            if let Some(alt) = m.alignment_alt {
                assert!((alt as usize) < c.alignments.len(), "{}", m.name);
            }
        }
    }

    #[test]
    fn shop_weighting_favours_cheap_gear() {
        assert!(shop_total_weight() > 0.0);
        let club = items().iter().find(|i| i.name == "Club").unwrap();
        let plate = items().iter().find(|i| i.name == "Plate").unwrap();
        let weight = |i: &Item| (i.cost as f64).powf(SHOP_GAMMA);
        assert!(
            weight(club) > weight(plate) * 5.0,
            "a Club should be far likelier to stock than Plate"
        );
    }
}
